version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: "wait-for-it.sh web:3000 -- npm test"
    depends_on: 
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.calculator
    command: "npm start"
    expose:
      - "3000"
