version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bash -c "wait-for-it.sh webapp:3000 && npm test"
    links:
      - webapp
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: npm start
    tty: true
    expose:
      - "3000"